image:
  file: .gitpod.dockerfile

tasks:
  - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &

vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - streetsidesoftware.code-spell-checker
    - christian-kohler.path-intellisense
    - dbaeumer.vscode-eslint
    - ms-python.debugpy
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - njpwerner.autodocstring
    - vscode-icons-team.vscode-icons
    - yzhang.markdown-all-in-one
