# Generated by Django 3.2.20 on 2024-02-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='basket_item_count',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='delivery_order_date',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='purchase_order_date',
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='address_line_1',
            field=models.CharField(default='Information not provided', max_length=60),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='address_line_2',
            field=models.CharField(default='Information not provided', max_length=60),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='city',
            field=models.CharField(default='Information not provided', max_length=60),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='county',
            field=models.CharField(default='Information not provided', max_length=20),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='first_name',
            field=models.CharField(blank=True, default='Information not provided', max_length=30),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='last_name',
            field=models.CharField(blank=True, default='Information not provided', max_length=30),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='memorable_name',
            field=models.CharField(default='Information not provided', max_length=60),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='post_code',
            field=models.CharField(default='Information not provided', max_length=15),
        ),
    ]
