# Generated by Django 3.2.20 on 2023-09-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='delivery_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='purchase_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
