# Generated by Django 3.2.20 on 2024-02-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_accounts', '0002_auto_20240217_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='county',
            field=models.CharField(default='Information not provided', max_length=30),
        ),
    ]
