# Generated by Django 3.2.20 on 2023-10-09 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_accounts", "0003_auto_20230927_0529"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraccount",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("N", "Prefer not to say"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="memorable_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="memorable_name",
            field=models.CharField(default="Your Memorable Name", max_length=60),
        ),
        migrations.AlterField(
            model_name="customeraccount",
            name="address_line_1",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="customeraccount",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^(((\\+44\\s?\\d{4}|\\(?0\\d{4}\\)?)\\s?\\d{3}\\s?\\d{3})|((\\+44\\s?\\d{3}|\\(?0\\d{3}\\)?)\\s?\\d{3}\\s?\\d{4})|((\\+44\\s?\\d{2}|\\(?0\\d{2}\\)?)\\s?\\d{4}\\s?\\d{4}))(\\s?\\#(\\d{4}|\\d{3}))?$"
                    )
                ],
            ),
        ),
    ]
