# Generated by Django 3.2.20 on 2024-02-18 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_accounts', '0003_alter_customeraccount_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(regex='^(((\\+44\\s?\\d{4}|\\(?0\\d{4}\\)?)\\s?\\d{3}\\s?\\d{3})|((\\+44\\s?\\d{3}|\\(?0\\d{3}\\)?)\\s?\\d{3}\\s?\\d{4})|((\\+44\\s?\\d{2}|\\(?0\\d{2}\\)?)\\s?\\d{4}\\s?\\d{4}))(\\s?\\#(\\d{4}|\\d{3}))?$')]),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='post_code',
            field=models.CharField(default='Information not provided', max_length=20),
        ),
    ]
