# Generated by Django 3.2.20 on 2024-02-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_accounts', '0004_auto_20240218_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='post_code',
            field=models.CharField(default='Information not provided', max_length=30),
        ),
    ]
