# Generated by Django 3.2.20 on 2023-08-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='featured_image',
        ),
    ]
