# Generated by Django 3.2.20 on 2024-03-24 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_post_excerpt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="excerpt",
        ),
    ]
