# Generated by Django 3.2.20 on 2023-09-07 06:34

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colour',
            new_name='CakeColour',
        ),
        migrations.RenameModel(
            old_name='Flavour',
            new_name='CakeFlavour',
        ),
        migrations.RenameModel(
            old_name='Cake',
            new_name='IndividualCake',
        ),
        migrations.CreateModel(
            name='CakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cakes.individualcake')),
            ],
        ),
    ]
