# Generated by Django 3.2.20 on 2024-03-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_auto_20240226_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakecategory',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
