# Generated by Django 3.2.20 on 2024-03-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0003_alter_cakecategory_category"),
    ]

    operations = []
