# Generated by Django 3.2.20 on 2023-09-25 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cakes", "0007_auto_20230922_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualcake",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="cakes.cakecategory",
            ),
        ),
    ]
